packages:
  - "apps/*"
  - "packages/*"
  - "vendor/wterm/packages/@wterm/*"
  - "vendor/wterm/packages/@internal/*"
  - "!vendor/wterm/packages/@wterm/dom"
  - "!vendor/wterm/packages/@wterm/just-bash"
  - "!vendor/wterm/packages/@wterm/markdown"
  - "!vendor/wterm/packages/@wterm/react"
  - "!vendor/wterm/packages/@wterm/vue"

onlyBuiltDependencies:
  - node-pty

catalog:
  zod: 4.4.3
